### ISSUE TITLE
Ctrtransfer 2.1.0 failed at step 3

### ISSUE THREAD

**Issue by sthetix** [Plailect/Guide#525] opened 2016-09-18 00:55 UTC
I am using the latest decrypt9wip on my downgraded N3DS (9.2) and always failed at step 3.

```
Initializing SD card... success
Build: Decrypt9WIP (2016/08/14)
Work directory: /files9
Game directory: /files9
sector0x96 Key: otp.bin not found
0x03 KeyX & KeyY: already set up
0x05 KeyY: already set up
0x25 KeyX: already set up
0x18 KeyX: already set up
0x1B KeyX: not found
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: partially failed

You selected [Auto CTRNAND Transfer].

This feature writes to the SysNAND.
This may overwrite important data!

If you wish to proceed, enter:
<Left>, <Up>, <Right>, <Up>, <A>

(B to return, START to reboot)

Selected: [Auto CTRNAND Transfer]
A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
Use arrow keys and <A> to choose a file
2.1.0-4U_ctrtransfer_o3ds.bin

Step #0: Optional NAND backup
Press <B> to skip and continue without backup
Dumping SysNAND. Size (MB): 1240
Use arrow keys and <A> to choose a name
(cancelled by user)

Step #1: .SHA verification of CTRNAND image...
Checking hash from .SHA file...
Step #1 success!

Step #2: Dumping transfer files
Searching for movable.sed...
Found at 0E748000, size 320b
Creating B95C44CF_movable.sed ...
Searching for ticket.db...
Found at 0B9F8000, size 35MB
Creating B95C44CF_ticket.db ...
Searching for configsave.bin...
Found at 0F258000, size 256kB
Creating B95C44CF_configsave.bin ...
Searching for LocalFriendCodeSeed_B...
Found at 0E6D0000, size 272b
Creating B95C44CF_LocalFriendCodeSeed_B ...
Searching for SecureInfo_A...
Found at 0E788000, size 273b
Creating B95C44CF_SecureInfo_A ...
Step #2 success!

Step #3: Injecting CTRNAND transfer image
Switching out NAND header first...
Auto CTRNAND Transfer: failed!

Press B to return, START to reboot.
```

Anybody how to fix this?

**Comment by FrozenChen** [comment] 2016-09-18 03:38
>Decrypt9WIP (2016/08/14)
For starters, use the LATEST RELEASE OF DECRYPT9WIP
If that ctrnand transfer actually went through you would have a nice brick
Get the latest release and remember the next time to follow instructions exactly
[https://github.com/d0k3/Decrypt9WIP/releases/](url)

**Comment by pbanj** [comment] 2016-09-18 04:09
also MAKE A FUCKING NAND BACKUP. if that had gone worse your 3ds would have been dead without a nand backup

**Comment by sthetix** [comment] 2016-09-18 07:59
Well, i tried latest version of DecryptWip and still the same.
And I have the NAND backup.


```
Initializing SD card... success
Build: Decrypt9WIP (2016/08/23)
Work directory: /files9
Game directory: /files9
sector0x96 Key: otp.bin not found
0x03 KeyX & KeyY: already set up
0x05 KeyY: already set up
0x25 KeyX: already set up
0x18 KeyX: already set up
0x1B KeyX: not found
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: partially failed

You selected [Auto CTRNAND Transfer].

This feature writes to the SysNAND.
This may overwrite important data!

If you wish to proceed, enter:
<Left>, <Up>, <Right>, <Up>, <A>

(B to return, START to reboot)

Selected: [Auto CTRNAND Transfer]
A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
Use arrow keys and <A> to choose a file
2.1.0-4U_ctrtransfer_o3ds.bin
Image size is: 794624000 byte

Step #0: Optional NAND backup
Press <B> to skip and continue without backup
Dumping SysNAND. Size (MB): 1240
Use arrow keys and <A> to choose a name
(cancelled by user)

Step #1: .SHA verification of CTRNAND image...
Checking hash from .SHA file...
Step #1 success!

Step #2: Dumping transfer files
Searching for SecureInfo_A...
Found at 0E788000, size 273b
Creating B95C44CF_SecureInfo_A ...
Searching for movable.sed...
Found at 0E748000, size 320b
Creating B95C44CF_movable.sed ...
Searching for LocalFriendCodeSeed_B...
Found at 0E6D0000, size 272b
Creating B95C44CF_LocalFriendCodeSeed_B ...
Searching for configsave.bin...
Found at 0F258000, size 256kB
Creating B95C44CF_configsave.bin ...
Step #2 success!

Step #3: Injecting CTRNAND transfer image
Switching out NAND header first...
Auto CTRNAND Transfer: failed!

Press B to return, START to reboot.
```

**Comment by Ev1lbl0w** [comment] 2016-09-18 09:34
0x03 KeyX & KeyY: already set up
0x05 KeyY: already set up
0x25 KeyX: already set up
0x18 KeyX: already set up
**0x1B KeyX: not found**
0x24 KeyY: automatically set up

Try getting that bin file and putting it in the root of your SD card or in the files9 folder.

**Comment by sthetix** [comment] 2016-09-18 10:14
Yes, still the same 

```
Initializing SD card... success
Build: Decrypt9WIP (2016/08/23)
Work directory: /files9
Game directory: /files9
sector0x96 Key: otp.bin not found
0x03 KeyX & KeyY: already set up
0x05 KeyY: already set up
0x25 KeyX: already set up
0x18 KeyX: already set up
0x1B KeyX: loaded, verified, set up
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: success!

You selected [Auto CTRNAND Transfer].

This feature writes to the SysNAND.
This may overwrite important data!

If you wish to proceed, enter:
<Left>, <Up>, <Right>, <Up>, <A>

(B to return, START to reboot)

Selected: [Auto CTRNAND Transfer]
A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
Use arrow keys and <A> to choose a file
2.1.0-4U_ctrtransfer_o3ds.bin
Image size is: 794624000 byte

Step #0: Optional NAND backup
Press <B> to skip and continue without backup
Dumping SysNAND. Size (MB): 1240
Use arrow keys and <A> to choose a name
(cancelled by user)

Step #1: .SHA verification of CTRNAND image...
Checking hash from .SHA file...
Step #1 success!

Step #2: Dumping transfer files
Searching for SecureInfo_A...
Found at 0E788000, size 273b
Creating B95C44CF_SecureInfo_A ...
Searching for movable.sed...
Found at 0E748000, size 320b
Creating B95C44CF_movable.sed ...
Searching for LocalFriendCodeSeed_B...
Found at 0E6D0000, size 272b
Creating B95C44CF_LocalFriendCodeSeed_B ...
Searching for configsave.bin...
Found at 0F258000, size 256kB
Creating B95C44CF_configsave.bin ...
Step #2 success!

Step #3: Injecting CTRNAND transfer image
Switching out NAND header first...
Auto CTRNAND Transfer: failed!

Press B to return, START to reboot.
Initializing SD card... success
Build: Decrypt9WIP (2016/08/23)
Work directory: /files9
Game directory: /files9
sector0x96 Key: otp.bin not found
0x03 KeyX & KeyY: already set up
0x05 KeyY: already set up
0x25 KeyX: already set up
0x18 KeyX: already set up
0x1B KeyX: loaded, verified, set up
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: success!

You selected [Auto CTRNAND Transfer].

This feature writes to the SysNAND.
This may overwrite important data!

If you wish to proceed, enter:
<Left>, <Up>, <Right>, <Up>, <A>

(B to return, START to reboot)

Selected: [Auto CTRNAND Transfer]
A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
Use arrow keys and <A> to choose a file
2.1.0-4U_ctrtransfer_o3ds.bin
Image size is: 794624000 byte

Step #0: Optional NAND backup
Press <B> to skip and continue without backup
Dumping SysNAND. Size (MB): 1240
Use arrow keys and <A> to choose a name
(cancelled by user)

Step #1: .SHA verification of CTRNAND image...
Checking hash from .SHA file...
Step #1 success!

Step #2: Dumping transfer files
Searching for SecureInfo_A...
Found at 0E788000, size 273b
Creating B95C44CF_SecureInfo_A ...
Searching for movable.sed...
Found at 0E748000, size 320b
Creating B95C44CF_movable.sed ...
Searching for LocalFriendCodeSeed_B...
Found at 0E6D0000, size 272b
Creating B95C44CF_LocalFriendCodeSeed_B ...
Searching for configsave.bin...
Found at 0F258000, size 256kB
Creating B95C44CF_configsave.bin ...
Step #2 success!

Step #3: Injecting CTRNAND transfer image
Switching out NAND header first...
Auto CTRNAND Transfer: failed!

Press B to return, START to reboot.
```

**Comment by Ev1lbl0w** [comment] 2016-09-18 11:01
You probably have a partial downgrade. You didn't have any error during the 9.2 downgrade?

I'd say to try downgrading to 9.2 again.

**Comment by sthetix** [comment] 2016-09-18 11:06
First time downgrade there was an error. So i could not run decrypt9wip..but then i downgraded it again and decrypt9wip worked.

 i have tried to downgrade this console several times and no errors

**Comment by Ev1lbl0w** [comment] 2016-09-18 11:15
weird, wait for a more technical person to help you then...

**Comment by sthetix** [comment] 2016-09-18 11:33
Actually i have dumped the nand with hardmod method before downgrading it (although it was on 10.7).
The nand chip is samsung, and nand size is 1,954,545,664 bytes

The nand size is not listed in plailect guide.

**Comment by Ev1lbl0w** [comment] 2016-09-18 11:43
Firstly, finally someone can tell @Plailect who is the manufacturer of the Unknown NAND xD.

Secondly, since you have a hardmod, why don't you try doing a NAND backup, then restoring the stock NAND backup and try doing it all over again?

**Comment by sthetix** [comment] 2016-09-18 12:59
The NANDmin.bin dumped with Decrypt9WIP is 1,300,234,240 bytes 
different from the hardmod version 1,954,545,664 bytes

**Comment by ihaveamac** [comment] 2016-09-18 13:42
min-size dumps are always 1,300,234,240 bytes, because it's only used space. everything after is unused.

**Comment by sthetix** [comment] 2016-09-18 15:39
I successfully restore the console to stock nand 10.7.0 32 U, then successfully downgrade it to 9.2
but then the i faced same problem at the same spot.
I cannot continue after failing at step#3 at ctrtransfer.

```
Initializing SD card... success
Build: Decrypt9WIP (2016/08/23)
Work directory: /files9
Game directory: /files9
sector0x96 Key: otp.bin not found
0x03 KeyX & KeyY: already set up
0x05 KeyY: already set up
0x25 KeyX: already set up
0x18 KeyX: already set up
0x1B KeyX: loaded, verified, set up
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: success!

You selected [Auto CTRNAND Transfer].

This feature writes to the SysNAND.
This may overwrite important data!

If you wish to proceed, enter:
<Left>, <Up>, <Right>, <Up>, <A>

(B to return, START to reboot)

Selected: [Auto CTRNAND Transfer]
A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
Use arrow keys and <A> to choose a file
2.1.0-4U_ctrtransfer_o3ds.bin
Image size is: 794624000 byte

Step #0: Optional NAND backup
Press <B> to skip and continue without backup
Dumping SysNAND. Size (MB): 1240
Use arrow keys and <A> to choose a name
NANDmin.bin
Creating NANDmin.bin ...
NAND dump SHA256: B5798252...
Store to NANDmin.bin.sha: ok

Step #1: .SHA verification of CTRNAND image...
Checking hash from .SHA file...
Step #1 success!

Step #2: Dumping transfer files
Searching for SecureInfo_A...
Found at 0E788000, size 273b
Creating B95C44CF_SecureInfo_A ...
Searching for movable.sed...
Found at 0E748000, size 320b
Creating B95C44CF_movable.sed ...
Searching for LocalFriendCodeSeed_B...
Found at 0E6D0000, size 272b
Creating B95C44CF_LocalFriendCodeSeed_B ...
Searching for configsave.bin...
Found at 0F258000, size 256kB
Creating B95C44CF_configsave.bin ...
Step #2 success!

Step #3: Injecting CTRNAND transfer image
Switching out NAND header first...
Auto CTRNAND Transfer: failed!

Press B to return, START to reboot.




```

**Comment by Plailect** [comment] 2016-09-19 02:25
Duplicate of https://github.com/d0k3/Decrypt9WIP/issues/94

**Closed by Plailect** 2016-09-19 02:25 UTC
