### ISSUE TITLE
Can't update my SysNand

### ISSUE THREAD

**Issue by SpaceCraft33** [Plailect/Guide#718] opened 2016-11-22 23:53 UTC
Hi, I create my own issues instead of posting in another one.

I'm currently with a N3DS with Sys 9.0.0-20E written and i'm stuck at Section IV of the guide. I can't update my system. I tried to restore my Nand that I got from the first part of the tutorial, but nothing. Can't update, the N3DS just reboot after saying that it didn't work (the internet connexion works)

What am I doing wrong ?

Thank you :)

**Comment by Plailect** [comment] 2016-11-23 00:15
duplicate of https://github.com/Plailect/Guide/issues/716

**Closed by Plailect** 2016-11-23 00:15 UTC
