### ISSUE TITLE
3DS Freezes

### ISSUE THREAD

**Issue by RayMafnas** [Plailect/Guide#412] opened 2016-08-28 02:50 UTC
When I try to access Nintendo DS Connections on Internet settings is this normal or did I mess up something? On AL9H firmware is updated to 11, and also when I was updating my system from 9.2 I kept getting an error and had to retry for like 10 time before it updated is that normal?

**Comment by Plailect** [comment] 2016-08-28 04:13
I need a detailed account of what you did.

**Comment by RayMafnas** [comment] 2016-08-28 06:21
I followed the guide step by step on my 2DS ver. 6.0.0U then on part 3 Section IV - Restoring the System i got a blackscreen and tried all the steps and troubleshooting but nothing worked so I did a 9.2.0 CTRtransfer and got it working, then updated my firmware to 11.0 (it failed alot of times), everything is working fine I mean I have installed CIA's and played them, then I was tinkering with my settings and came upon this freeze while trying to access DS connections

**Comment by TheAquaSheep** [comment] 2016-08-28 11:30
As mentioned in the closed issue, this also affects me.
I started on 7.1.0-16E but had to ctrtransfer to 9.2.0 at the same point as RayMafnas due to black screen.
I then upgraded to 11.0.0-33E without issue via settings and system transferred my NNID from another 3ds

I hadn't checked Nintendo DS settings until a few minutes ago

**Comment by Ev1lbl0w** [comment] 2016-08-28 15:37
Just to be sure, did you both used Gateway software in the past?

**Comment by jaxrogers2** [comment] 2016-08-28 15:51
This could be caused by some leftovers from MSET of some sort (Gateway or otherwise).

**Comment by TheAquaSheep** [comment] 2016-08-28 16:23
In my case, it was an (almost) vanilla console. I had previously used ninjhax 1.1b to boot homebrew launcher without doing much else but look at the cool cube demo.

**Comment by jaxrogers2** [comment] 2016-08-28 17:40
Hmmm... Ninjhax 1.1b can mess some things up on 9.3+ systems because it used rohax, which was patched in 9.3 so that could be causing it.

**Comment by RayMafnas** [comment] 2016-08-28 19:15
My 2DS was straight otta the box.. just make me a lil nervous that it might be a ticking bomb or something, (paranoid)

**Comment by jaxrogers2** [comment] 2016-08-28 19:25
Did you ever open Nintendo DS connections before the downgrade? It could be that you just never initialized the save data for the application, or that if you opened it on 6.X (which has MSET capability) and then updated with A9LH, so new save data isn't created because there is save data from 6.X that the system is trying to load but can't because Nintendo DS connections was updated? I don't really know. I haven't gone through the process of getting A9LH (old guide or new guide) on a <9.3 system, so I'm not sure.

**Comment by RayMafnas** [comment] 2016-08-28 19:50
No I didnt open Nintendo DS connections before the downgrade. I will try to access ds connections with a game

**Comment by TheAquaSheep** [comment] 2016-08-28 19:58
It could be a save data initialization problem. I assume there would be a specific folder to delete to test this?
As for deleting ninjhax 1.1b, I don't understand the logic here. Since I have A9LH, I have no need for ninjhax of any sort.
It is safely there on my sky3ds for using homebrew on old systems.
I just tried to use a DS game - Pokemon Black - to test the connection settings menu there, but I find I black screen on this too, suggesting a TWL_FIRM issue as mentioned.
(note that the DS game test was performed on 9.2.0 A9LH after I restored my 7.1.0 and ctrtransferred again.
I will go full vanilla and retest

**Comment by RayMafnas** [comment] 2016-08-28 20:30
Same issues here tested a game Mario Kart DS  managed to get into the game running on 11.0 freeze when I try to set up a connection or go online

**Comment by Margen67** [comment] 2016-08-29 05:44
Have you tried booting DS connections through FBI?

**Comment by TheAquaSheep** [comment] 2016-08-29 12:43
I tried what I think is DS connections via FBI but got a black screen.
I also tried Zelda Four Swords (DSi mode title) and Legends of Exidia via both home menu and FBI and black screened on both.

**Comment by Ev1lbl0w** [comment] 2016-08-30 13:23
I'm no expert on this, but could this thread on GBATemp help you @Plailect ? (http://gbatemp.net/threads/ctrnand-transfer-also-transfers-other-consoles-ticket-db-etc-it-can-remove-your-bad-tickets.439802/#post-6641039)

**Comment by RayMafnas** [comment] 2016-08-31 00:28
3 Days and still no advise by Plailect, I just want to start over and follow the old guide even though its longer does anyone here any the complete guide? its no longer available in this page, im really new to this but I have installed AL9H on an O3DS and that one seems to be working fine with no hiccups, could someone walk me through how to uninstall a9lh or start anew?

**Comment by dark-samus** [comment] 2016-08-31 00:29
It is available here: https://github.com/Plailect/Guide_RedNAND/wiki

**Comment by RayMafnas** [comment] 2016-08-31 02:56
thank you dark-samus!

**Comment by Ev1lbl0w** [comment] 2016-08-31 12:02
@RayMafnas don't be impatient. Plailect is looking for the source of this problem, since you're not the only one. Even if you do the old guide, DS Modde will probably still be messed up. So, stop. Don't do anything until Plailect finds a solution.

**Comment by Plailect** [comment] 2016-08-31 17:50
Consolidating into https://github.com/Plailect/Guide/issues/438

**Closed by Plailect** 2016-08-31 17:50 UTC

**Comment by RayMafnas** [comment] 2016-09-01 01:24
Its all working now, just installed the CIA on two 2DS and both are playing DSi games and stuff! :D thanks guys
