### ISSUE TITLE
Add suggestion for safehax r19

### ISSUE THREAD

**Issue by CorrosiveCat** [Plailect/Guide#1050] opened 2017-04-30 18:49 UTC
As many people who have 11.2 or below have experienced the PM_INIT_FAILED error, a note should be added to suggest r19 for these versions if this error occurs with r21

**Comment by Plailect** [comment] 2017-05-02 19:50
duplicate of https://github.com/Plailect/Guide/issues/1042

**Closed by Plailect** 2017-05-02 19:50 UTC
