### ISSUE TITLE
noob1234

### ISSUE THREAD

**Issue by KratZ88** [Plailect/Guide#60] opened 2016-04-08 04:30 UTC
Hi Plailect, 

I was the one talking to you in the #3dshacks channel on Rizon IRC. I have tried to re-download the OTPhelper.zip and replace both the arm files, but the browser still freezes. 

This is what I have tried:
1. Changing to other SD card (copy and paste the whole SD card to another)
2. Replacing the file over many times
3. Re-downloading the .zip file and replacing the file
4. Using older older build arm files (up to ver. 0.80) and someone in the channel did advised me to try ver. 0.50 (I did too)
5. Doing no.2 - no.4 in other SD cards too

Do you have any other solutions?

**Comment by Plailect** [comment] 2016-04-08 10:56
What is your browser version? (it's in the browser settings at the bottom)

**Comment by KratZ88** [comment] 2016-04-08 19:38
1.7455

**Comment by Plailect** [comment] 2016-04-08 21:00
Contact @d0k3, I'm not sure what the issue is.

**Comment by d0k3** [comment] 2016-04-08 21:12
I don't have an idea either, just saying. Maybe @b1l1s knows something? He did the 2xrsa entrypoint.

**Comment by b1l1s** [comment] 2016-04-09 05:49
No clue neither, but most probably a partial. Try running rx 2.5.1 and recover/downgrade again from there if possible.

**Comment by Plailect** [comment] 2016-04-09 05:52
Can't be a partial, we verify all .tmd and .app files now before copying to SysNAND to prevent exactly that.

**Comment by KratZ88** [comment] 2016-04-09 07:38
So what should I do now? Running rx tool?

**Comment by d0k3** [comment] 2016-04-09 08:53
Seconding that. A partial is absolutely impossible using the standard method (One Click Setup). KratZ88 did use that, right? 

And yes, try rxTools v2.5.1 to restore your previous SysNAND backup. You can then downgrade again, hoping it will work this time.

**Comment by b1l1s** [comment] 2016-04-09 08:59
Well if 2.5.1 runs then it is a partial. Nothing to lose by trying it out anyway.

**Comment by KratZ88** [comment] 2016-04-09 08:59
Yes I used the one click setup, have been following the guide carefully. So I just install rxtools via fbi, am I correct?

**Comment by KratZ88** [comment] 2016-04-09 09:04
Just to be sure, after I have restore my sysnand, I just need to downgrade again, which is to follow part 4 section 2 -  downgrading, right?

**Comment by KratZ88** [comment] 2016-04-09 14:09
Guys, I was trying to update my firmware to 4.X to install rxtools using sky3ds+ and harvest moon a new beginning, at first try it gave me error and on the second try it gave me error right after updating. 

And now everything I turn on my new 3ds, it gives me error. Do you know what is going on? Here is the link to the picture. 

http://imgur.com/18Lcz08

**Comment by mariogamer2** [comment] 2016-04-09 18:03
Everityme on sysNAND?

Brick....

**Comment by b1l1s** [comment] 2016-04-09 19:40
What @mariogamer2 said.

The point of using rx 2.5.1 was to try and recover without using a cart to upgrade..
Your option right now is to hardmod and reflash your nand with the backup you made. Ask around in \#3dshacks on how to do that.

**Comment by Plailect** [comment] 2016-04-09 19:43
You have bricked and will need to restore with a hardmod.

I still don't know what the original issue was, but I'm closing this until it's reproducible.

**Closed by Plailect** 2016-04-09 19:43 UTC

**Comment by KratZ88** [comment] 2016-04-11 09:35
@b1l1s , is there any other way to install rx 2.5.1 without having to upgrade to firmware 4.X? Yep, doing a hardmod right now

**Comment by b1l1s** [comment] 2016-04-12 07:35
Just copy the files to your sdcard and launch it using spider.

**Comment by KratZ88** [comment] 2016-04-12 08:38
Hmm.. Sorry I don't understand spider, do you gave any links explaining how to launch rxtools using spider?
