### ISSUE TITLE
When will the guide use the latest A9LH boot without SD in the Full Guide?

### ISSUE THREAD

**Issue by SirBeethoven** [Plailect/Guide#425] opened 2016-08-29 22:36 UTC
Awesome guide!! By the way, is the latest A9LH (v2) still being developed? It seems to be pretty stable. If so, could you possibly add it as the default option in the guide? Thanks for everything!

**Comment by sora10pls** [comment] 2016-08-30 01:30
According to some people, not released = unstable beta software.

The latest commit of AuroraWright's fork of A9LH is working perfectly for myself and many others, so I too would like to see that changed in the guide some time in the future.

**Comment by Margen67** [comment] 2016-08-30 06:37
Possible duplicate of #396

**Comment by jaxrogers2** [comment] 2016-08-31 03:10
Yeah, this is a duplicate of 396. This guide already uses (AuroraWright's) A9LH V2, you're probably thinking about the AuroraWright A9LH that can boot without SD. Essentially, the guide will not add this build of A9LH that can load without the SD until it is introduced into a proper AuroraWright A9LH release. However, you are free to install this SD bootless version of AuroraWright's A9LH by compiling the fork yourself or finding precompiled builds here at https://m.reddit.com/r/3dshacks/comments/4p3ycq/aurora_wrights_arm9loaderhax_fork_updated_merges/ and follow the instructions.

**Comment by SirBeethoven** [comment] 2016-08-31 11:54
Yes, it seems to be. I'm just wondering if Plailect will ever add it to the FULL guide

**Comment by Plailect** [comment] 2016-08-31 17:08
When it's released, duplicate of https://github.com/Plailect/Guide/issues/396

**Closed by Plailect** 2016-08-31 17:08 UTC

**Comment by SirBeethoven** [comment] 2016-08-31 21:16
Ok thanks :)
