### ISSUE TITLE
Black screen on SysNAND boot after installing arm9loaderhax

### ISSUE THREAD

**Issue by tsuncp** [Plailect/Guide#137] opened 2016-05-18 23:08 UTC
HELP... 

After installation of arm9loaderhax, it reboots . and then forever black screen.

I have tried 

Ensure you have a working payload.
Check for the existence of arm9loaderhax.bin in the root of your SD card.
Check that
/luma/firmware.bin exist; and
/luma/firmware.bin is the correct one for your console.
Try resetting Luma's config and fix options
Delete /luma/config.bin from your SD card
Set your options when it boots
Test booting Decrypt9
On Luma3DS, hold Start on boot
Try this test payload (mirror).
Rename /arm9loaderhax.bin, if it exists, to something else.
Place the arm9loaderhax.bin from the archive linked above in your SD root.
Insert your SD card into your 3DS and power on.
Press A. Your 3DS should power off; this means arm9loaderhax is working and something else is broken; your device is not bricked.

still black screen....

**Comment by dbw-holic** [comment] 2016-05-19 00:12
From memory, after installing arm9loaderhax, the only options would be "Press any key to shut down", isn't it?

**Comment by tsuncp** [comment] 2016-05-19 00:15
Yes. 

I am planning to hardmod 3ds , recovering the sysnand from sysNAND_original.bin generated in part 4 .

Will it work?

**Comment by Plailect** [comment] 2016-05-19 01:07
Did you use the correct OTP? The only way this should be possible is on old 3ds by using an invalid OTP.bin.

**Comment by tsuncp** [comment] 2016-05-19 01:11
My device is new 3dsll and the installation has verified the otp.bin is
valid

Maybe there is some problem in the micro sd card or my card reader ? I am
using 64kb and 64gb card. Windows always reports there is an error.
「Plailect <notifications@github.com>」在 2016年5月19日 週四，09:07 寫道：

**Comment by dbw-holic** [comment] 2016-05-19 01:22
I have seen people having same issue (getting black screen) caused by microSD card on GBATEMP. Maybe take a look into the card?

**Comment by dbw-holic** [comment] 2016-05-19 01:24
Or, although that would be very unlikely, it could be hardware issue. I am just saying one of the possibilities, not commenting against your situation.

**Comment by tsuncp** [comment] 2016-05-19 01:27
Hoping hackmod can save my life. I was cracking the device for my fd. If it
cannot be recovered..............:(((((((
「dbw-holic <notifications@github.com>」在 2016年5月19日 週四，09:23 寫道：

**Comment by tsuncp** [comment] 2016-05-19 01:29
So if I am right that I am going to recover the sysnand from the original
version backed up on step4 ?
「dbw-holic <notifications@github.com>」在 2016年5月19日 週四，09:25 寫道：

**Comment by Kikoshi** [comment] 2016-05-19 01:40
how did you format your sd card? Is it with Easus?
try a different formater if that's the case

**Comment by tsuncp** [comment] 2016-05-19 01:49
http://www.ridgecrop.demon.co.uk/index.htm?guiformat.htm

I tried two sd card. While installing the arm9loaderhax, the 64gb and 64kb
allocation unit size card was using.

However, now I can't start 3ds with or without the sd card.both of them
getting same result,black screen



「Kikoshi <notifications@github.com>」在 2016年5月19日 週四，09:40 寫道：

**Comment by Kikoshi** [comment] 2016-05-19 02:19
redo Step 5 (Section I - Preparatory work)
Make sure you are nameing and placing the files in their correct location, also format the card as default. Use https://www.sdcard.org/downloads/formatter_4/ see if this works for you and if you do get it to boot, backup your SDcard and format it with EMU9(this will give you 64kb allocation and follow the instructions since it will wipe your card ;) ).

**Comment by Plailect** [comment] 2016-05-19 20:37
If it hangs on a black screen with no sd card, you are probably bricked and will need a hardmod.

Closing this issue as this is not really a troubleshooting forum.

**Closed by Plailect** 2016-05-19 20:37 UTC
