### ISSUE TITLE
The newest arm9loaderhax builds can boot without the SD card!

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#603] opened 2016-10-08 04:04 UTC
The new A9LH builds include the SD-less boot commit, so people with A9LH installed can now boot without the SD card, so you might want to take that sentence out at the end of Part 3. Just give a warning not to update via SAFE_MODE without an SD card in as this does not have FIRM protection on an SD-Less boot. Updating through normal system settings I believe has FIRM protection though even on an SD-Less boot, but the guide should probably just instruct people to not update their console without the SD card inserted just as a precaution.

**Comment by ihaveamac** [comment] 2016-10-08 05:42
there are no official releases of this yet.

**Comment by Margen67** [comment] 2016-10-08 09:21
Duplicate of #396 and #238

**Comment by jaxrogers2** [comment] 2016-10-08 13:52
That's strange, I wonder why the builds don't include those 2 commits since the new builds came out yesterday.

**Closed** 2016-10-08 13:52 UTC

**Comment by Plailect** [comment] 2016-10-11 00:41
The reboot patch isn't functional on the NAND minicfw in that commit.
