### ISSUE TITLE
Suggesting it here because it's on an image.

### ISSUE THREAD

**Issue by mmands994** [Plailect/Guide#1196] opened 2017-06-07 01:06 UTC
For [this ](https://3ds.guide/images/screenshots/final-file-layout.png)image, I would suggest adding the "DCIM" folder there, because that's where the photos are kept. We don't want people deleting those.

**Comment by Plailect** [comment] 2017-06-07 05:21
Duplicate of #1154

**Closed by Plailect** 2017-06-07 05:21 UTC
